holla({
    "words": [
        "playa",
        "gansta",
        "dope",
        "tight",
        "chill",
        "dat",
        "dem",
        "sup?",
        "ho",
        "flava",
        "phat",
        "busta",
        "cuz",
        "bizzle",
        "fizzle",
        "hizzle",
        "rizzle",
        "shizzle",
        "tizzle",
        "bumpin",
        "diss",
        "booty",
        "dank",
        "dub",
        "dubs",
        "thug",
        "wanksta",
        "chillax",
        "crib",
        "hood",
        "bling",
        "kool",
        "tight",
        "wack",
        "boo",
        "shorty",
        "peeps",
        "homie",
        "hoodrat",
        "boyz",
        "dabomb",
        "mybad",
        "oldskool",
        "newskool",
        "wordup",
        "dilly",
        "hustle",
        "O.G.",
        "trippin",
        "crunk",
        "jiggy",
        "twerk"
     ],
    "numbers": [420, 213, 313, 808, 247, 69, 187],
    "leetChars": {
        "A": [4, "@"],
        "B": [8],
        "C": ["("],
        "E": [3],
        "G": [6],
        "I": [1, "!"],
        "O": [0],
        "S": [5, "$"],
        "T": [7, "+"],
        "X": ["%"],
        "Z": [2]
    },
})
